changesets CI
Signed-off-by: NishkarshRaj <nishkarshraj000@gmail.com>

diff --git a/.github/workflows/validation.yml b/.github/workflows/validation.yml
--- a/.github/workflows/validation.yml
+++ b/.github/workflows/validation.yml
@@ -18,5 +18,29 @@ jobs:
         with:
           node-version: 16
 
-      - name: Install dependencies
-        run: npm ci
+      - name: Install Dependencies
+        run: |
+          npm ci
+          npm i -g yarn
+        
+      # Assuming changesets are mandatory for PRs
+      - name: Changeset Detector
+        run: |
+          cp -rf .changeset /tmp/.changeset
+          git fetch origin main
+          git checkout main
+
+          # Diff returns 0 if no difference
+          # Diff returns 1 if difference b/w directories
+          # CI exits whenever exit code $? is non-zero
+
+          set +e # Disable exit on error
+          diff .changeset /tmp/.changeset
+          flag=$?
+          set -e # Enable exit on error
+          if [ $flag -ne 1 ]
+          then
+            exit 1
+          else
+            exit 0
+          fi
